package com.it.ynzl.main.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table trs_users
 */
@ApiModel(value = "用户信息")
@Data
@TableName(value = "talentresource.trs_users")
public class User implements Serializable {
    @ApiModelProperty(value = "id")
    private String id;

    @ApiModelProperty(value = "用户名")
    private String username;

    @ApiModelProperty(value = "密码")
    private String password;

    @ApiModelProperty(value = "单位id")
    private String unitId;

    @ApiModelProperty(value = "用户类型 管理员，普通")
    private Integer type;

    @ApiModelProperty(value = "token")
    private String token;

    @ApiModelProperty(value = "省代码")
    private String provinceCode;

    @ApiModelProperty(value = "市代码")
    private String cityCode;

    @ApiModelProperty(value = "区县代码")
    private String countyCode;

    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    @ApiModelProperty(value = "修改时间")
    private Date updateTime;

    @ApiModelProperty(value = "删除时间")
    private Date deleteTime;

    @ApiModelProperty(value = "登录过期时间")
    private Date endTime;

    @ApiModelProperty(value = "删除标志 0-正常 其他-删除")
    private Integer deleteFlag;

    @ApiModelProperty(value = "激活状态 0-禁用 1-激活")
    private Integer activeStatus;
}